In [2]:
from la_libreria.authentication import Credentials
from la_libreria.connectors import MySQLConnector

In [3]:
creds_d= Credentials().load(path="Credentials/db_dev.json")
creds_p= Credentials().load(path="Credentials/db_prod.json")

Credentials loaded from: Credentials/db_dev.json
Credentials loaded from: Credentials/db_prod.json

In [17]:
conn_d = MySQLConnector(creds_d.dict).connect()
conn_p = MySQLConnector(creds_p.dict).connect()

In [24]:
conn_d.get_data("SHOW TABLES").set_index("Tables_in_defaultdb")

Empty DataFrame
Columns: []
Index: [cdc, curated, datos_transformados, delivery, macro_data, metric_table, model_tracking, monitoreo, predicciones, stock_data, tracking_modelos]

# Predicciones

In [8]:
conn_d.get_data("select * from predicciones")

         Date Ticker     5Days    10Days    30Days
0  2023-11-16  ^GSPC -0.016146 -0.009313 -0.034422
1  2025-04-21  ^GSPC -0.017838 -0.010064 -0.036552
2  2025-06-24  ^GSPC  1.379360  1.440970  0.521741

# Model tracking (ML FLOW)

In [13]:
conn_p.get_data("select * from model_tracking").head()

,Timestamp,Target,nombre_modelo,n_train,n_test,features,parametros,metric_name,metric_value,last_date,first_date,Ticker,training_time,prediction_time
0,1757890039.2116432,5,LinearRegression,24485,1,"[""Open"", ""Close"", ""High"", ""Low"", ""Volume"", ""re...","{""copy_X"": true, ""fit_intercept"": true, ""n_job...",mae,None,2025-6-24,1927-12-30,^GSPC,0.131608,0.004138
1,1757890044.680194,10,LinearRegression,24485,1,"[""Open"", ""Close"", ""High"", ""Low"", ""Volume"", ""re...","{""copy_X"": true, ""fit_intercept"": true, ""n_job...",mae,None,2025-6-24,1927-12-30,^GSPC,0.075047,0.001976
2,1757890049.9177208,30,LinearRegression,24485,1,"[""Open"", ""Close"", ""High"", ""Low"", ""Volume"", ""re...","{""copy_X"": true, ""fit_intercept"": true, ""n_job...",mae,None,2025-6-24,1927-12-30,^GSPC,0.130266,0.002473
3,1757891604.0608895,5,LinearRegression,24485,1,"[""Open"", ""Close"", ""High"", ""Low"", ""Volume"", ""re...","{""copy_X"": true, ""fit_intercept"": true, ""n_job...",mae,None,2025-6-24,1927-12-30,^GSPC,0.032314,0.001789
4,1757891609.2749798,10,LinearRegression,24485,1,"[""Open"", ""Close"", ""High"", ""Low"", ""Volume"", ""re...","{""copy_X"": true, ""fit_intercept"": true, ""n_job...",mae,None,2025-6-24,1927-12-30,^GSPC,0.022058,0.001622

# Monitoreo Metricas

In [14]:
conn_d.get_data("select * from metric_table")

        Date       MAE Ticker Days
0  2025-4-21  0.010559  ^GSPC   10
1  2025-4-21  0.029401  ^GSPC   30

In [15]:
conn_d.close()
conn_p.close()

Connection closed
Connection closed

# Listado de modelos

In [29]:
import os
models = os.listdir("Models")
print("30 dias:")
for m in models:
    if m.split("_")[1]=="30":
        print("\t",m)
print("10 dias:")
for m in models:
    if m.split("_")[1]=="10":
        print("\t",m)
print("5 dias:")
for m in models:
    if m.split("_")[1]=="5":
        print("\t",m)

30 dias:
	 modelo_30_^GSPC_2025-09-21_23:31:35.joblib
	 modelo_30_^GSPC_2025-09-21_21:39:48.joblib
	 modelo_30_^GSPC_2025-09-21_11:20:51.joblib
10 dias:
	 modelo_10_^GSPC_2025-09-21_21:39:41.joblib
	 modelo_10_^GSPC_2025-09-21_11:20:45.joblib
	 modelo_10_^GSPC_2025-09-21_23:31:28.joblib
5 dias:
	 modelo_5_^GSPC_2025-09-21_19:43:25.joblib
	 modelo_5_^GSPC_2025-09-21_21:39:28.joblib
	 modelo_5_^GSPC_2025-09-21_21:37:36.joblib
	 modelo_5_^GSPC_2025-09-21_23:31:15.joblib
	 modelo_5_^GSPC_2025-09-21_11:20:37.joblib