In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
from ETL.ingesta_yahoo import obtener_datos_yahoo
from ETL.ingesta_fred import obtener_datos_fred

In [21]:
yahoo = obtener_datos_yahoo(ticker="TSLA", start= None,end=None)
fred = obtener_datos_fred(start=None, end=None)

[*********************100%***********************]  1 of 1 completed

In [24]:
while len(fred) > 1:
    fred[0] = pd.concat([fred[0], fred[-1]], axis=1)
    fred.pop(-1)
fred = fred[0]

In [ ]:
fred.head()

            UNRATE  CPIAUCSL   DFF  PCE  INDPRO  DGS10  FEDFUNDS
2025-04-05     NaN       NaN  4.33  NaN     NaN    NaN       NaN
2025-04-06     NaN       NaN  4.33  NaN     NaN    NaN       NaN
2025-04-07     NaN       NaN  4.33  NaN     NaN   4.15       NaN
2025-04-08     NaN       NaN  4.33  NaN     NaN   4.26       NaN
2025-04-09     NaN       NaN  4.33  NaN     NaN   4.34       NaN

In [26]:
yahoo.head()

               Close      High       Low      Open     Volume
2010-06-29  1.592667  1.666667  1.169333  1.266667  281494500
2010-06-30  1.588667  2.028000  1.553333  1.719333  257806500
2010-07-01  1.464000  1.728000  1.351333  1.666667  123282000
2010-07-02  1.280000  1.540000  1.247333  1.533333   77097000
2010-07-06  1.074000  1.333333  1.055333  1.333333  103003500